### ISSUE TITLE
hdwallet - send

### ISSUE THREAD

**Issue by elegant651** [epitomecl/kmp-wallet#15]
transfer to coin via json-rpc

- [x] bind with blockchain.info libraries
- [x] resolve dependencies on dagger
- [x] implement to simple ui
- [x] testing : connect to server node

**Comment by elegant651** [comment]
mywallethd.jar => package info.blockchain.api.interfaces;  

rest 로 호출하는것으로 보아, server 에 bitcoinj-api wrapper 있어야함. https://github.com/blockchain/api-v1-client-node 같은 것들

**Comment by jsyun-epi** [comment]
Will님 작업하신거 참고해서 작업중인데 server쪽 api 구현 가능한지 확인해보겠습니다.

**Comment by elegant651** [comment]
네. 아마, send 쪽 코드가 아마 많이 바뀔것 같습니다. 기존 my-wallet 라이브러리를 가져오다보니, dagger dependency 문제가 있어서 아키텍처를 변경할 듯 해요

**Comment by elegant651** [comment]
bitcoind-testnet-faucet : https://testnet.coinfaucet.eu/
